version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run: pip3 install . --user
      # The tests
      - run:
          command: pytest -W error::UserWarning --cov blacktex
          working_directory: test/
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
